import { Analytics } from '@vercel/analytics/react';
import React from 'react';
import RootStyleRegistry from './emotion';

export const metadata = {
  title: 'Todo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-Hans-CN">
      <body>
        <RootStyleRegistry>{children}</RootStyleRegistry>
        <Analytics />
      </body>
    </html>
  );
}
