import { Analytics } from '@vercel/analytics/react';
import React from 'react';
import RootStyleRegistry from '@/components/emotion';
import ModalsRegistry from '@/components/modals';
import DatesRegistry from '@/components/dates';
import NotificationsRegistry from '@/components/notifications';

export const metadata = {
  title: 'Todo',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh-Hans-CN">
      <body>
        <RootStyleRegistry>
          <ModalsRegistry>
            <DatesRegistry>
              {children}
              <NotificationsRegistry />
            </DatesRegistry>
          </ModalsRegistry>
        </RootStyleRegistry>
        <Analytics />
      </body>
    </html>
  );
}
