import { MantineProviderProps } from '@mantine/core';
import React from 'react';
import RootStyleRegistry from './emotion';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: React.FC<MantineProviderProps> = ({ children }) => {
  return (
    <html lang="zh-Hans-CN">
      <body>
        <RootStyleRegistry>{children}</RootStyleRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
